[project]
name = "potential-happiness"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "scikit-datasets"
]

[project.optional-dependencies]
dev = [
    "black",
    "mypy",
    "notebook",
    "graphviz",
    "pytest",
    "numpy",
    "torch",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
disable_error_code = ["import-untyped"]
